name: Build and Release tdraw.dll

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get release tag from GITHUB_REF
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Build tdraw.dll
      run: |
        msbuild src/DDraw/ddraw.vcxproj /p:Configuration=ReleasePublic /p:Platform=x86
      working-directory: ${{ github.workspace }}

    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          src/DDraw/Public/tdraw.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
